# serverless.yml

service: contact-form-api

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs14.17.6
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-2
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    # EMAIL: ${self:custom.secrets.EMAIL}
    EMAIL: ${jasonmiller.dev@gmail.com}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
